### ISSUE TITLE
normalization explanation

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#12]
I'm sufficiently confused by the following sentence that I can't reword it:  "Figure 8 shows major nuclides which have strong influence on the reactor core physics normalized separately for each isotope by average atomic density, at the beginning of each depletion timestep."

**Comment by andrewryh** [comment]
Okay, I don't know how to rephrase it.

What I mean here:

**Comment by andrewryh** [comment]
In my thesis, it was normalized by average but in the paper, I have changed it to absolute atomic density. Fixed!
