### ISSUE TITLE
Confusing statement

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#13]
...zone I produced much more thermal neutrons than zone II, indicating that the majority of fissions occured in the central part of the core...

Thermal neutrons cause fission, not the other way around. Fissions cause fast neutrons. Moderation causes thermal neutrons. Yes, fissions and thermal neutrons must co-exist, but perhaps it's clearer to say :
 
...zone I produced more thermal neutrons than zone II, corresponding to a majority of fissions occuring in the central part of the core...

**Comment by andrewryh** [comment]
Right, zone I contains most of fission because it has nice fuel-moderator ratio. Thanks for the clearer statement, fixed!
