### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#15]
I think the opposite of this statement is true. 

> When the graphite temperature increases, the density of graphite decreases creating additional space for fuel salt.

I believe this is true:

> When the graphite temperature **decreases**, the density of graphite decreases creating additional space for fuel salt.

**Comment by andrewryh** [comment]
@katyhuff I cannot agree. I didn't find T vs density plot in Robertson but here is one for some graphite:
![dependence-of-the-relative-density-of-pyrolytic-graphite-on-temperature-in-comparison_w640](https://user-images.githubusercontent.com/20629016/44481068-8705fb00-a60a-11e8-8084-0228c9660c12.jpg)
Reference: https://www.researchgate.net/publication/320995261_Experimental_investigation_of_linear_thermal_expansion_of_pyrolytic_graphite_at_high_temperatures

In fact, I have taken a linear expansion coefficient from Robertson (1.3E-6 1/K) and calculated new volume of the element for higher temperature 1000K. It was larger than for 900K.

Probably, I just didn't understand your point, please, clarify.

**Comment by katyhuff** [comment]
Sorry -- I was being an idiot and thought 'volume' rather than 'density'. Of course you're correct.

**Comment by andrewryh** [comment]
No worries, it happens with me all the time! :D
