### ISSUE TITLE
Final sentences

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#17]
The final sentences of the conclusions section seem like too much detail and not totally supported by the work.

> The existing full-core SERPENT 2 model and equilibrium fuel material composition would be
> employed to generate problem-oriented nuclear data libraries for further usage in accident
> transient analysis. The final goal of this effort is to develop a fast-running computational model
> which could study the dynamic behavior of generic MSRs, performing detailed safety analysis
> and design optimization for a variety of reactor concepts.

**Comment by andrewryh** [comment]
Removed
