### ISSUE TITLE
Comments Teddy

### ISSUE THREAD

**Issue by jbae11** [arfc/msbr-reproc#20]
Great Job Andrei!
[msbr-reproc.pdf](https://github.com/arfc/msbr-reproc/files/2333757/msbr-reproc.pdf)

**Comment by andrewryh** [comment]
@jbae11 Thanks for edits, I've implemented most of them.
Small comment: I cite in this paperSaltProc version 0.1.0 which doesn't have two-fluid support, etc. So, it will be in next papers.

**Comment by jbae11** [comment]
@andrewryh  sounds good !

**Comment by jbae11** [comment]
@andrewryh Can you close this once this is reflected in your paper? thanks!

**Comment by katyhuff** [comment]
@andrewryh : As you make edits in response to comments, it's best to make a single pull request addressing the comments in the issue, mention the issue, and request a review of that PR by the person who opened the issue. Then, when the PR is merged, you can close this issue and it's clear to everyone involved what's been accomplished.
