### ISSUE TITLE
Comments - Gwen

### ISSUE THREAD

**Issue by gwenchee** [arfc/msbr-reproc#22]
Cool Paper Andrei! Here are my comments (my comments only start from page 18 onwards): 
[msbr-reproc-gwenedits.pdf](https://github.com/arfc/msbr-reproc/files/2340668/msbr-reproc-gwenedits.pdf)

**Comment by andrewryh** [comment]
Thanks for the feedback! Edits were implemented.

**Comment by katyhuff** [comment]
@andrewryh were all the edits implemented? If so, this should be closed.

**Comment by katyhuff** [comment]
Can you please pull request that work into this fork so this issue can be closed?
