### ISSUE TITLE
Review - Park

### ISSUE THREAD

**Issue by smpark7** [arfc/msbr-reproc#23]
Here are my comments. Good luck!

[msbr-reproc-review-park.pdf](https://github.com/arfc/msbr-reproc/files/2341743/msbr-reproc-review-park.pdf)

**Comment by andrewryh** [comment]
Thanks for edits, done!

**Comment by katyhuff** [comment]
@andrewryh Please close issues with PRs... I think the issues raised here were handled with 0e164365dfb6b36381552d16637d080fbf8f8834, is that right? Can you please pull request that work into this fork so this issue can be closed?
