### ISSUE TITLE
Confusing lit review words. Please clarify.

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#25]
In lines 40-60, I'm confused about which methods employ batchwise and which employ a continous approach. 

I think it's appropriate to add the word also to the paragraph below, to be more clear:

> ORNL researchers have developed ChemTriton, a Python-based script for SCALE/TRITON which uses the batch-wise approach to simulate a continuous reprocessing. ChemTriton models salt treatment, separations, discharge, and refill using a unit-cell MSR SCALE/TRITON depletion simulation over small time steps to simulate continuous reprocessing and deplete the fuel salt [27]. Methods listed in references [14, 17, 24, 25, 28, 29, 30] as well as the current work **also** employ a batch-wise approach.

Similarly, I suspect the word "Meanwhile" in the following paragraph is misleading. Meanwhile is usually used to indicate a contrast between two similar things. For example "Jenny was an exceptional student. Meanwhile, her twin sister Jessy was always in trouble. "

> Accounting for continuous removal or addition presents a greater challenge 55 since it requires adding a term to the Bateman equations. In SCALE [26], ORIGEN [16] solves a set of Bateman equations using spectrum-averaged fluxes and cross sections generated from a deterministic transport calculation. Meanwhile, approaches listed in references [11, 12, 19, 31] model true continuous feeds and removals.

In the above paragraph, are you trying to indicate that the methods in [11, 12, 19, 31] use this SCALE/ORIGEN capability, or that they use some other strategy and thereby acheive continuous feeds and removals much like this SCALE/ORIGEN capability?

**Comment by andrewryh** [comment]
> In the above paragraph, are you trying to indicate that the methods in [11, 12, 19, 31] use this SCALE/ORIGEN capability, or that they use some other strategy and thereby achieve continuous feeds and removals much like this SCALE/ORIGEN capability?

No, none of them use SCALE/ORIGEN. Will fix it

**Comment by andrewryh** [comment]
> In lines 40-60, I'm confused about which methods employ batchwise and which employ a continous approach

It is clarified here:
> Accounting for continuous removal or addition presents a greater challenge since it requires adding a term to the Bateman equations. Aufiero \emph{et al.} explicitly
introduced online fuel reprocessing in the system of equations by adding effective decay and transmutation terms for the different nuclides. In his work SERPENT was 
used for solution of the matrix exponential derived from the system of the Bateman 
equations \cite{aufiero_extended_2013}. Similar approach is adopted to model true 
continuous feeds and removals using MCNP transport code listed in references 
\cite{doligez_coupled_2014,heuer_towards_2014,nuttin_potential_2005}.

I am happy to add a column in table **continuous/batch-wise** but there is no space to do this.

**Comment by andrewryh** [comment]
@katyhuff I've messed up with this multiple PRs, so, I've pushed graphical abstract and lit review changes in **PR after group mates comments #24**.
Should I remove my commits and make it again with new PR?

**Comment by katyhuff** [comment]
no need to remove commits, I just wanted that big PR to be closed. It's merged now so we can close this.
