### ISSUE TITLE
Graphical Abstract can only contain one image

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#26]
The graphical abstract guidelines are [thus](https://www.elsevier.com/journals/annals-of-nuclear-energy/0306-4549/guide-for-authors):

> Although a graphical abstract is optional, its use is encouraged as it draws more attention to the online article. The graphical abstract should summarize the contents of the article in a concise, pictorial form designed to capture the attention of a wide readership. Graphical abstracts should be submitted as a separate file in the online submission system. Image size: Please provide an image with a minimum of 531 × 1328 pixels (h × w) or proportionally more. The image should be readable at a size of 5 × 13 cm using a regular screen resolution of 96 dpi. Preferred file types: TIFF, EPS, PDF or MS Office files. You can view Example Graphical Abstracts on our information site. Authors can make use of Elsevier's Illustration Services to ensure the best presentation of their images and in accordance with all technical requirements.

The graphical abstract currently includes all the figures. **Please pick just one that is representative of the article.**

**Comment by katyhuff** [comment]
Two figures can also be combined into a single image for the graphical abstract. I'd recommend one or more of the following:

![keff_rem_cases](https://user-images.githubusercontent.com/393899/45163994-20aadc00-b1b7-11e8-95e5-d89b253ba174.png)
![radial_flux](https://user-images.githubusercontent.com/393899/45164004-299bad80-b1b7-11e8-9dbb-3889f27f41e2.png)
![ser_zone_ii](https://user-images.githubusercontent.com/393899/45164053-43d58b80-b1b7-11e8-955c-a463ff86c1d9.png)
![spectrum_zones](https://user-images.githubusercontent.com/393899/45164079-4f28b700-b1b7-11e8-9fe3-f4ae001c594e.png)

**Comment by katyhuff** [comment]
I think this was handled in #24 ?

**Comment by andrewryh** [comment]
Yes, everything in #24

**Comment by katyhuff** [comment]
See: https://github.com/arfc/msbr-reproc/commit/a53f7ec99b6c08a01f48e37006295adc5e19dcf4#diff-52420d3b6473fae9dad6a9c65b1711ecR59
