### ISSUE TITLE
Figure captions say "both" but only one graph is shown

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#29]
I just noticed: Figures 13 and 14 say : 

- Figure 13: Normalized power density for both initial and equilibrium fuel salt composition.
- Figure 14: 232Th neutron capture reaction rate normalized by total flux for both initial and equilibrium fuel salt composition.

But, only one plot is shown for each. Maybe two plots were intended??

**Comment by andrewryh** [comment]
It is a bug.
It were two plots in my thesis but they look very similar for initial and equilibrium, so, I left only one of them.
