### ISSUE TITLE
Temperature feedback: add row with density and Doppler in Table 5

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#31]
Reviewer 2:

- [x]  "The main physical principle underlying the reactor temperature feedback is an expansion of material that is heated". This sentence would deserve some support data. Can you please calculate separately the effect of temperature (Doppler in fuel and spectral shift in graphite) and density?
- [x]  How uncertainties have been calculated in Table 5? Is this just statistical uncertainty from Serpent calculations? Please clarify
- [x] For calculating the coefficients in table 5, are you only changing densities, or also dimensions? Please clarify and provide a justification. 
- [x]  "The fuel temperature coefficient (FTC) is negative for both initial and equilibrium fuel compositions due to thermal Doppler broadening of the resonance capture cross sections in the thorium." What is the effect of density?

**Comment by katyhuff** [comment]
closed with #36
