### ISSUE TITLE
Reviewer #1: minor comments

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#32]
- [x] Abstract: Given the recent announcement about TransAtomic Power, you may want to remove them from your list?
- [x] Table 1, page 3: SCALE/TRITON is fast as well as thermal reactor capable. 
- [x] Page 4, Line 48: Should read "...and refill using a single or multiple unit cell ...."
- [x] Page 4, Line 55. Also worth noting that the latest SCALE release will have the same functionality using continuous removal (B. R. Betzler, J. J. Powers, N. R. Brown, and B. T. Rearden, "Molten Salt Reactor Neutronics Tools in SCALE," Proc. M&C 2017 - International Conference on Mathematics & Computational Methods Applied to Nuclear Science and Engineering, Jeju, Korea, Apr. 16-20 (2017).)
- [x] Page 8, Fig 2: Appears the image is cut off at the top?
- [x] Page 13, line 209: The description of the Pa removal, although correct, isn't quite fully correct. The reason the Pa is removed from the core and hence flux is to then enable the Pa to decay to U233. If it was left in the core, it would transmute further and hence not be able to produce the U233 that is necessary for this breeding cycle to work.
- [x] Table 3: "cycle time" is not defined in the paper. Please add.
- [x] Page 14, line 224. The 3 day time step as the "optimum" for Th fuel cycles in an MSR was first described and concluded by Powers et al. Please add a reference to their initial work.
- [x] Page 18, line 327: Are those elements removed every 3435 days, or is it that the entire salt core is discharged?
- [x] Page 19, Figure 8 (and same for Fig 9): y-axis in grams/kgs or mass units would be better for the reader.
- [x] Page 20, Fig 9: What are the wiggles and dips , especially seen for Np235?
- [x] Page 20, line 351: It is more than just the Pu isotopes that makes the spectrum harder? What about the other MAs etc?
- [x] Fig 12: units on y-axis?
- [x] Page 24, line 389: Should that be "233U" and not "233Th"?
- [x] Table 5: Please provide some comments on the uncertainties - where do they come from? Also, the "reference" results need to state whether "initial" or "equilibrium"
- [x] Page 26, line 425: "Relatively large" compared with what? Perhaps results for an LWR case would be a good basis for comparison?
- [x] Page 27, section 3.8: It needs to be made more clear that these results were calculated, and that they are taken from the code output.

**Comment by andrewryh** [comment]
>  Page 19, Figure 8 (and same for Fig 9): y-axis in grams/kgs or mass units would be better for the reader.

Is hard to implement because the first version of SaltProc store in the database only atomic density, so, I can plot without recalculation only atomic density.
Many authors (e.g. Park et al.) plotted number density not a mass, so, can we deny this comment?

**Comment by katyhuff** [comment]
> Page 19, Figure 8 (and same for Fig 9): y-axis in grams/kgs or mass units would be better for the reader.

For comparison publication-to-publication with other work, atom density was chosen, although mass would certainly be more understandable for the reader (in a vacuum).

**Comment by katyhuff** [comment]
closed with #36
