### ISSUE TITLE
K-eff and Th refill graphs are hard to read due to huge swings (Reviewer #1)

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#33]
Discussion needed to resolve these comments:

- [x] Page 18, Figure 7: The figure is hard to interpret or see clearly what is going on. Could an additional figure or a zoomed in portion be added to show what the swing in k is over a much shorter time interval? k seems to be swinging dramatically but over what time period and how would this be controlled in reality? The graph almost suggests that the core is unstable??
- [x] Page 29, Figure 15: Similar comment to above regarding Fig 7 - the results are difficult to see and interpret with such notable swings.

**Comment by andrewryh** [comment]
Figure 7
![keff](https://user-images.githubusercontent.com/20629016/50597086-cae7f700-0e6b-11e9-832c-762eba26d931.png)
Figure 15
![th_refill_rate](https://user-images.githubusercontent.com/20629016/50597098-d0ddd800-0e6b-11e9-817e-482554d13dc8.png)

**Comment by andrewryh** [comment]
Alternative #1: Plot average Keff ( (BOC+EOC)/2 )
![1](https://user-images.githubusercontent.com/20629016/50597348-c243f080-0e6c-11e9-8260-a3d0283beee5.png)

**Comment by andrewryh** [comment]
Alternative #2: Add Figure with a a shorter timeframe (0-220days, because every 50 days we are removing rare earths, 60 days - Br, I; 200 days - Zr, Cd, In, Sn): 
![2](https://user-images.githubusercontent.com/20629016/50598453-6da27480-0e70-11e9-9d89-fd2f8021b7c7.png)

Or 3400-3480 range to show Rb, Sr, Cs, Ba removal every 3435 days:
![2_2](https://user-images.githubusercontent.com/20629016/50598650-ff11e680-0e70-11e9-835b-1511cbf38c2a.png)

Or 3300-3550:
![2_3](https://user-images.githubusercontent.com/20629016/50598755-5adc6f80-0e71-11e9-9fd9-8669d1bb02e3.png)

Or 30-543 days (Eu removing every 500days):
![2_4](https://user-images.githubusercontent.com/20629016/50599552-0ab2dc80-0e74-11e9-9004-b7ce383d5911.png)

**Comment by katyhuff** [comment]
![image](https://user-images.githubusercontent.com/393899/50613899-c4c23c80-0ea4-11e9-973a-334e0fa2fa1d.png)
example ^^^

**Comment by katyhuff** [comment]
closed with #36 #42
