### ISSUE TITLE
Reviewer #3 minor comments

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#35]
- [x] 1. What are the main differences of this work with the previous works, especially with the work published by Park at al. in "Whole core analysis of molten salt breeder reactor with online fuel reprocessing"?
- [x] 2. How did the authors verify the coupled SaltProc and Serpent code system? 
- [x] 3. In Page 3, the title of "Table 1" should not only contain the "fast spectrum system". The work published by Zhou and Yang et al. with the title of "Fuel cycle analysis of molten salt reactors based on coupled neutronics and thermal-hydraulics calculations" needs to be included in Table 1 for completeness.
- [x] 5. In Page 10, "SERPENT generates the problem-dependent nuclear data library", how did SERPENT generate the problem-dependent nuclear data library? What kind of nuclear data library did SERPENT generate?
- [x] 6. In Page 14, "depletioncalculations" should be "depletion calculations".
- [x] 7. In Page 21, it looks like the neutron spectrum is not normalized in Figure 10. It is recommended to normalize the neutron spectrum for comparison.
- [x] 8. In Page 22, "Figure 13 reflects the normalized power distribution of the MSBR quarter core, which is the same at both the initial and equilibrium states" contradicts the following statement of "The spectral shift during reactor operation results in different power fractions at startup and equilibrium".
- [x] 9. In Page 24, it is hard to agree with the statement that "the majority of 233Th is produced in zone II.". How did the authors draw this conclusion?
- [x] 10. In Page 24 and 25, why did the normalized power density distribution and the 232Th neutron capture reaction rate distribution share the same figure for both initial and equilibrium fuel salt compositions?
- [ ] 11. Too much background information was contained in the abstract, which deteriorates the readability of the abstract.

Reviewer 2 (comments related with Reviewer 3):
- [x] Can the proposed tool adjust reactivity?

**Comment by andrewryh** [comment]
> In Page 21, it looks like the neutron spectrum is not normalized in Figure 10. It is recommended to normalize the neutron spectrum for comparison.

What does it mean normalized? 
In my case integral under the spectrum curve =1 (calculate by numpy.trapz).
Probably, he meant some other type of normalization? By average?
I have no idea.

**Comment by katyhuff** [comment]
>  2. How did the authors verify the coupled SaltProc and Serpent code system? 

Remind the reviewer that we mention comparison to Ben, and made some comparison with Park. Note that future releases will contain significant generalization of the method as well as a suite of unit tests. 

> 7. In Page 21, it looks like the neutron spectrum is not normalized in Figure 10. It is recommended to normalize the neutron spectrum for comparison.

Tell the reviewer that this is per lethargy and the area under the curve is normalized to 1. (add the normalization under the curve to the caption)

>  11. Too much background information was contained in the abstract, which deteriorates the readability of the abstract.

@katyhuff can work on this.
