### ISSUE TITLE
Reviewer 2: numerical approximations vs physics assumptions

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#38]
> In the manuscript it is not always clear when the authors refer to numerical approximations of physical situations. For instance, the authors write "Figure 16 demonstrates that batch-wise removal of strong absorbers every 3 days did not necessarily leads to fluctuation in results but rare earth elements 480 removal every 50 days causes an approximately 600 pcm jump in reactivity." These 600 pcm are an effect of a numerical approximation, but the way things are presented can be confusing to the reader. Please try to explicitly separate physical and numerical effects. And try to related numerical effects to physical effects. For instance, how does these numerical "jumps" affect the results?  In this sense, why the batch-wise removal of strong absorbers every 3 days  was not done? And why a fraction of rare earths  is not removed every three days?

I totally can't understand what Reviewer 2 wanna from me. Completely

**Comment by katyhuff** [comment]
I can try this one. (probably related to the other comments already handled).

**Comment by katyhuff** [comment]
closed with #36
