### ISSUE TITLE
Review Changes

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#45]
Review all of the changes by looking over this pdf:  
[msbr-reproc-diff.pdf](https://github.com/arfc/msbr-reproc/files/2728636/msbr-reproc-diff.pdf)

- [x] Andrei review complete
- [x] Katy review complete 
- [x] Teddy review complete 

( @jbae11 , if you don't have time to look this over, that's fine, I just want to make sure you're ok with the final submission since your name is on it. We're submitting tomorrow.)

**Comment by andrewryh** [comment]
Everything looks fine except last three tables in Results are all in the end of Results...
Probably, it happens due to diff script running..

**Comment by jbae11** [comment]
I have very minor comments:

- abstract
    - `advanced nuclear energy' -> advanced nuclear technologies
    - liquid fueled -> liquid-fueled (inconsistent throughout paper)

- line 255 is a bit confusing (in blue)
    - would produce a smaller amount of Pa233 which ~
    - consider: `Pa233, if left in the core, will produce Pa234 or U234, neither of which are useful as fuel. The desired isotope is U233, which is a decay product of Pa233. Accordingly ~'

- table 5 formatting?
- line 589
    - `to include online reprocessing in liquid-fueled MSR operation' -> `~ online reprocessing modeling capabilities'

**Comment by katyhuff** [comment]
closed with #47 47
