### ISSUE TITLE
Abstract should be restructured

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#5]
The abstract is somewhat confusing, I think because it doesn't follow the structure I usually expect. Here are two possible approaches to structuring an abstract:  

http://s3-service-broker-live-19ea8b98-4d41-4cb4-be4c-d68f4963b7dd.s3.amazonaws.com/uploads/ckeditor/attachments/7808/2c_Summary_para.pdf

http://mitcommlab.mit.edu/be/commkit/journal-article-abstract/

From the MIT one, we should fit the following into 5-8 sentences:

**General Background.** Something that everyone in your audience cares about. (e.g. climate change, safety, licensing molten salt reactors)
**Specific Background.** Zoom in from the thing everyone cares about to the thing you did. (i.e. people need tools for analyzing liquid fueled molten salt reactor depletion and fuel processing)
**Statement of Problem or Knowledge Gap.** What specific problem or phenomenon do we not understand in this field of study? (i.e. needed a high fidelity wrapper for serpent)
**Here we show.** One sentence about what you learned or did, and how that fulfills the demonstrated gap. (i.e. describe saltproc)
**Approach & Results.** Only the very highest-level methodology results. So what? What do your results mean for the thing everyone cares about? (i.e. SaltProc was demonstrated for the MSBR and compared well to previous results from lower fidelity analyses.)

**Comment by andrewryh** [comment]
Thanks for very helpful and super-detailed instruction! Abstract is still pain for me.
