### ISSUE TITLE
Table 1

### ISSUE THREAD

**Issue by katyhuff** [arfc/msbr-reproc#8]
I'm not sure about the use of Table 1. The distinction between "neutronic code" and "depletion code" isn't particularly clear. Instead of column 1, perhaps we could just refer to the works by their refs.

**Comment by andrewryh** [comment]
I will eliminate "Deletion code" column but if there are separate neutron transport and Bateman equations solvers I prefer explicitly mention it (i.e., SCALE/ORIGEN, MCNP6/CINDER90). Is it ok with you?

Column 1 redundant indeed, thanks

**Comment by katyhuff** [comment]
Sounds good.
